Check which nodes are actually in use
Before you had to manually update your hostlist after migrating to a
spare node. Now the list is all potential machines, including spares.
We actually connect and check if they have the targetNumID file in the
currently processing store folder.

Also now the nodes are actually in a random order which means I've
noticed that the RunData struct wasn't being saved when generating
parity - which means the rebuild failed.

diff --git a/bin/beegfs-parity-rebuild b/bin/beegfs-parity-rebuild
--- a/bin/beegfs-parity-rebuild
+++ b/bin/beegfs-parity-rebuild
@@ -49,6 +49,12 @@ if [ "`hostname -s`" != "s10n50" ]; then
     exit 1
 fi
 
+function collect_hostlist {
+    local full_hostlist="$1"
+    local store="$2"
+    cat "$full_hostlist" | xargs -n 1 -P 8 -I{} ssh {} "test -f $store/targetNumID && hostname -s; exit 0"
+}
+
 # Make sure all necessary folders are present
 mkdir --parents "/opt/$dname/run"
 mkdir --parents "/opt/$dname/spool"
@@ -56,11 +62,17 @@ mkdir --parents "/opt/$dname/spool"
 (
 if flock --exclusive --nonblock 500; then
     if [ ! -f "$last_successful_timestamp_file" ]; then
-        echo "** Error: Does not look like you have built any pariy" 1>&2
+        echo "** Error: Does not look like you have built any parity" 1>&2
         exit 1
     fi
 
-    hostfile="/opt/$dname/etc/hosts"
+    storage_nodes="/opt/$dname/etc/hosts"
+    hostfile="/opt/$dname/run/active_storage_nodes"
+    base_dir=`cat /opt/$dname/etc/basedir`
+    spool="/opt/$dname/spool/"
+    mkdir --parents $spool
+    collect_hostlist "$storage_nodes" "$base_dir" > "$hostfile"
+
     if ! grep -q "$rebuild_host" "$hostfile" ; then
         echo "** Error: Uknown host '$rebuild_host'" 1>&2
         exit 1
@@ -68,16 +80,13 @@ if flock --exclusive --nonblock 500; then
 
     rebuild_target=`awk "/$rebuild_host/ {print FNR-1}" "$hostfile"`
     safe_host=`comm -13 <(echo $rebuild_host) "/opt/$dname/etc/hosts" | head -n 1`
-    ssh $rebuild_host rm -rf /opt/$dname/spool/db
-    scp -pr $safe_host:/opt/$dname/spool/db $rebuild_host:/opt/$dname/spool/db
+    ssh $rebuild_host rm -rf $spool/db
+    scp -pr $safe_host:$spool/db $rebuild_host:$spool/db
 
-    base_dir=`cat /opt/$dname/etc/basedir`
-    spool="/opt/$dname/spool/"
-    mkdir --parents $spool
     echo `hostname -s` > /opt/$dname/run/hosts
-    cat "$hostfile" >> "/opt/$dname/run/hosts"
+    cat "$hostfile" >> /opt/$dname/run/hosts
     mpirun="mpirun --hostfile /opt/$dname/run/hosts"
-    $mpirun ./bp-parity-rebuild $rebuild_target $base_dir $spool/data /tmp/$base_dir-corrupted_chunks /opt/$dname/spool/db
+    $mpirun ./bp-parity-rebuild $rebuild_target $base_dir $spool/data /tmp/$base_dir-corrupted_chunks $spool/db
 
     # Collect list of potentially corrupt chunks
     for h in `cat /opt/$dname/etc/hosts`; do
